runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: numpy
  version: "1.6.1"

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]